ingresses:
- "https://emottak-sertifikatvalidator.dev.intern.nav.no"
signer:
  dn: "SERIALNUMBER=889640782,CN=ARBEIDS- OG VELFERDSETATEN,O=ARBEIDS- OG VELFERDSETATEN,C=NO"
truststore:
  file: {{ secrets.TRUSTSTORE_FILE_DEV }}
