ingresses:
- "https://emottak-sertifikatvalidator.dev.intern.nav.no"
signer:
  dn: "SERIALNUMBER=889640782,CN=ARBEIDS- OG VELFERDSETATEN,O=ARBEIDS- OG VELFERDSETATEN,C=NO"
buypass:
  dn: "CN=Buypass Class 3 Test4 CA 3, O=Buypass AS-983163327, C=NO"
  crl: "http://crl.test4.buypass.no/crl/BPClass3T4CA3.crl"
commfides:
  dn: "C=NO, O=Commfides Norge AS - 988 312 495, OU=CPN Enterprise-Norwegian SHA256 CA- TEST, OU=Commfides Trust Environment(C) 2014 Commfides Norge AS - TEST, CN=Commfides CPN Enterprise-Norwegian SHA256 CA - TEST"
  crl: "http://crl1.test.commfides.com/CommfidesEnterprise-SHA256.crl"