apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: emottak-sertifikatvalidator-truststore
  namespace: team-emottak
  labels:
    team: team-emottak
data:
  catruststore.jks: {{truststore}}
  catruststore_pass: {{truststorePass}}
