springdoc:
  api-docs:
    path: '/internal/api-docs'
  swagger-ui:
    path: '/internal/swagger'

management:
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health,prometheus'
      base-path: '/internal'
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
