springdoc:
  api-docs:
    path: '/internal/api-docs'
  swagger-ui:
    path: '/internal/swagger'

logging:
  level:
    web: INFO

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/v2.0
          #The client_id of this application
          accepted-audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

schedule:
  cron:
    cache:
      crl: '0 0 0 * * *'
      ssn: '0 0 1 * * *'

management:
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health,prometheus'
      base-path: '/internal'
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

ekstern:
  crlList:
    - dn: "CN=Buypass Class 3 Test4 CA 3, O=Buypass AS-983163327, C=NO"
      url: "http://crl.test4.buypass.no/crl/BPClass3T4CA3.crl"
    - dn: "C=NO, O=Commfides Norge AS - 988 312 495, OU=CPN Enterprise-Norwegian SHA256 CA- TEST, OU=Commfides Trust Environment(C) 2014 Commfides Norge AS - TEST, CN=Commfides CPN Enterprise-Norwegian SHA256 CA - TEST"
      url: "http://crl1.test.commfides.com/CommfidesEnterprise-SHA256.crl"
    - dn: "CN=Buypass Class 2 CA 2,O=Buypass AS-983163327,C=NO"
      url: "http://crl.buypass.no/crl/BPClass2CA2.crl"
    - dn: "CN=Buypass Class 3 CA 3,O=Buypass AS-983163327,C=NO"
      url: "http://crl.buypass.no/crl/BPClass3CA3.crl"