springdoc:
  api-docs:
    path: '/internal/api-docs'
  swagger-ui:
    path: '/internal/swagger'

logging:
  level:
    no.nav.emottak.sertifikatvalidator: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/v2.0
          #The client_id of this application
          accepted-audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

schedule:
  cron:
    cache:
      crl: '0 0 */6 * * *'
      ssn: '0 0 1 * * *'

management:
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health,prometheus'
      base-path: '/internal'
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

ekstern:
  caList:
      # Buypass prod
    - name: "Buypass Class 2 CA 2"
      dn: "CN=Buypass Class 2 CA 2,O=Buypass AS-983163327,C=NO"
      crlUrl: "http://crl.buypass.no/crl/BPClass2CA2.crl"
      ocspUrl: ""
      ocspSignerAlias: "nav_prod_nonrep"
    - name: "Buypass Class 3 CA 3"
      dn: "CN=Buypass Class 3 CA 3,O=Buypass AS-983163327,C=NO"
      crlUrl: "http://crl.buypass.no/crl/BPClass3CA3.crl"
      ocspUrl: "https://ocsp.prod.buypass.no/ocsp/BPClass3CA3"
      ocspSignerAlias: "nav_prod_nonrep"
    - name: "Buypass Class 3 CA G2 ST Business"
      dn: "CN=Buypass Class 3 CA G2 ST Business, O=Buypass AS, OID.2.5.4.97=NTRNO-983163327, C=NO"
      crlUrl: "http://crl.buypassca.com/BPCl3CaG2STBS.crl"
      ocspUrl: "http://ocspbs.buypassca.com"
      ocspSignerAlias: "nav_prod_nonrep"
    - name: "Buypass Class 3 CA G2 HT Person"
      dn: "CN=Buypass Class 3 CA G2 HT Person, O=Buypass AS, OID.2.5.4.97=NTRNO-983163327, C=NO"
      crlUrl: "http://crl.buypassca.com/BPCl3CaG2HTPS.crl"
      ocspUrl: "https://pno.buypassca.com"
      ocspSignerAlias: "nav_prod_nonrep"
    - name: "Buypass Class 3 CA G2 HT Business"
      dn: "CN=Buypass Class 3 CA G2 HT Business, O=Buypass AS, OID.2.5.4.97=NTRNO-983163327, C=NO"
      crlUrl: "http://crl.buypassca.com/BPCl3CaG2HTBS.crl"
      ocspUrl: "http://ocspbs.buypassca.com"
      ocspSignerAlias: "nav_prod_nonrep"
      # Buypass test
    - name: "Buypass Class 3 Test4 CA 3"
      dn: "CN=Buypass Class 3 Test4 CA 3, O=Buypass AS-983163327, C=NO"
      crlUrl: "http://crl.test4.buypass.no/crl/BPClass3T4CA3.crl"
      ocspUrl: "https://ocsp.test4.buypass.no/ocsp/BPClass3T4CA3"
      ocspSignerAlias: "nav_test4ca3_nonrep"
    - name: "Buypass Class 3 Test4 CA G2 ST Business"
      dn: "CN=Buypass Class 3 Test4 CA G2 ST Business, O=Buypass AS, OID.2.5.4.97=NTRNO-983163327, C=NO"
      crlUrl: "http://crl.test4.buypassca.com/BPCl3CaG2STBS.crl"
      ocspUrl: "http://ocspbs.test4.buypassca.com"
      ocspSignerAlias: "nav_test4ca3_nonrep"
    - name: "Buypass Class 3 Test4 CA G2 HT Person"
      dn: "CN=Buypass Class 3 Test4 CA G2 HT Person, O=Buypass AS, OID.2.5.4.97=NTRNO-983163327, C=NO"
      crlUrl: "http://crl.test4.buypassca.com/BPCl3CaG2HTPS.crl"
      ocspUrl: "https://pno.test4.buypassca.com"
      ocspSignerAlias: "nav_test4ca3_nonrep"
    - name: "Buypass Class 3 Test4 CA G2 HT Business"
      dn: "CN=Buypass Class 3 Test4 CA G2 HT Business, O=Buypass AS, OID.2.5.4.97=NTRNO-983163327, C=NO"
      crlUrl: "http://crl.test4.buypassca.com/BPCl3CaG2HTBS.crl"
      ocspUrl: "http://ocspbs.test4.buypassca.com"
      ocspSignerAlias: "nav_test4ca3_nonrep"
      # Commfides prod
    - name: "Commfides Legal Person - G3"
      dn: "CN=Commfides Legal Person - G3, OID.2.5.4.97=NTRNO-988312495, O=Commfides Norge AS, C=NO"
      crlUrl: "https://crl.commfides.com/G3/CommfidesLegalPersonCA-G3.crl"
      ocspUrl: "https://ocsp1.commfides.com/ocsp"
      ocspSignerAlias: "nav_prod_commfides_ocsp"
    - name: "Commfides Natural Person - G3"
      dn: "CN=Commfides Natural Person - G3, OID.2.5.4.97=NTRNO-988312495, O=Commfides Norge AS, C=NO"
      crlUrl: "https://crl.commfides.com/G3/CommfidesNaturalPersonCA-G3.crl"
      ocspUrl: "https://ocsp1.commfides.com/ocsp"
      ocspSignerAlias: "nav_prod_commfides_ocsp"
      # Commfides test
    - name: "Commfides CPN Enterprise-Norwegian SHA256 CA - TEST"
      dn: "C=NO, O=Commfides Norge AS - 988 312 495, OU=CPN Enterprise-Norwegian SHA256 CA- TEST, OU=Commfides Trust Environment(C) 2014 Commfides Norge AS - TEST, CN=Commfides CPN Enterprise-Norwegian SHA256 CA - TEST"
      crlUrl: "http://crl1.test.commfides.com/CommfidesEnterprise-SHA256.crl"
      ocspUrl: "https://ocsp1.test.commfides.com/ocsp"
      ocspSignerAlias: "nav_test_commfides_ocsp"
    - name: "Commfides Legal Person - G3 - TEST"
      dn: "CN=Commfides Legal Person - G3 - TEST, OID.2.5.4.97=NTRNO-988312495, O=Commfides Norge AS, C=NO"
      crlUrl: "https://crl.test.commfides.com/G3/CommfidesLegalPersonCA-G3-TEST.crl"
      ocspUrl: "https://ocsp1.test.commfides.com/ocsp"
      ocspSignerAlias: "nav_test_commfides_ocsp"
    - name: "Commfides Natural Person - G3 - TEST"
      dn: "CN=Commfides Natural Person - G3 - TEST, OID.2.5.4.97=NTRNO-988312495, O=Commfides Norge AS, C=NO"
      crlUrl: "https://crl.test.commfides.com/G3/CommfidesNaturalPersonCA-G3-TEST.crl"
      ocspUrl: "https://ocsp1.test.commfides.com/ocsp"
      ocspSignerAlias: "nav_test_commfides_ocsp"