name: "Build and deploy emottak-sertifikatvalidator"
on:
  push:
    branches:
    - "master"
env:
  "IMAGE": "docker.pkg.github.com/${{ github.repository }}/emottak-sertifikatvalidator:${{\
    \ github.sha }}"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/cache@v2"
      with:
        "path": "~/.m2/repository"
        "key": "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
        "restore-keys": "${{ runner.os }}-maven-"
    - uses: "actions/setup-java@v1"
      with:
        "java-version": "16"
    - name: "compile and run tests"
      run: "mvn install"
    - name: "Build and publish Docker image"
      run: "docker build --pull --tag ${IMAGE} . && echo $GITHUB_TOKEN | docker login\
        \ --username $GITHUB_REPOSITORY --password-stdin https://docker.pkg.github.com\
        \ && docker push ${IMAGE}"
      env:
        "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
  "deployAppToDev":
    name: "Deploy to dev"
    needs: "build"
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Deploy to DEV"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "dev-fss"
        "RESOURCE": ".nais/nais.yaml"
        "VARS": ".nais/dev.yaml"
  "deployAppToProd":
    name: "Deploy to prod"
    needs: "deployAppToDev"
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Deploy to PROD"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "prod-fss"
        "RESOURCE": ".nais/nais.yaml"
        "VARS": ".nais/prod.yaml"
